### ISSUE TITLE
typo in the comments

### ISSUE THREAD

**Issue by xxu36** [anakrish/oelldb#2]
The code is expected to get/set GPR values rather than Xstate values. There are typo in these two comments:
https://github.com/anakrish/oelldb/blob/f95e4936f5899b00f84c2b2e72c226af1c1695ad/ptraceLib/ptrace.c#L294
https://github.com/anakrish/oelldb/blob/f95e4936f5899b00f84c2b2e72c226af1c1695ad/ptraceLib/ptrace.c#L266

**Comment by anakrish** [comment]
@xxu36 Thanks for pointing out the typos.

I've a question about SGX's SSA area and ptrace:

Do we need to implement get/set of other fields in the `user` struct defined in `sys/user.h`:
   ```c
    struct user
    {
      struct user_regs_struct	regs;
      int				u_fpvalid;
      struct user_fpregs_struct	i387;
      __extension__ unsigned long long int	u_tsize;
      __extension__ unsigned long long int	u_dsize;
      __extension__ unsigned long long int	u_ssize;
      __extension__ unsigned long long int	start_code;
      __extension__ unsigned long long int	start_stack;
      __extension__ long long int		signal;
      int				reserved;
      __extension__ union
        {
          struct user_regs_struct*	u_ar0;
          __extension__ unsigned long long int	__u_ar0_word;
        };
      __extension__ union
        {
          struct user_fpregs_struct*	u_fpstate;
          __extension__ unsigned long long int	__u_fpstate_word;
        };
      __extension__ unsigned long long int	magic;
      char				u_comm [32];
      __extension__ unsigned long long int	u_debugreg [8];
    };
   ```
   I've implemented get/set only for `regs` member.

**Comment by xxu36** [comment]
@anakrish
SGX document mentions that SSA mainly contains two parts: 
1) GPR region (includes general purpose registers RAX … R15,  RIP, outside RSP and RBP, RFLAGS and the asynchronous exit information)
2) XSAVE region which contains extended feature register state. I think those information can all be obtained using current get/set handlers. 

So I think current implementation is OK. Besides, your code does not just handle `regs` member, `struct user_fpregs_struct` is also handled, for example, by the handler `sgx_get_fpr_handler`.

**Comment by anakrish** [comment]
Thanks for confirming @xxu36. I will go ahead and make a PR with the changes to OE repository.

Will close this issue for now since this repo is intended to be temporary.
Will make sure to fix the comments when the changes are pushed to OE repo.
